export default Uploader;
declare function Uploader({ accept: __accept, contentOverride: maybeContentOverride, innerIcon, innerText, action, className, minimal, validateAgainstSchema: _validateAgainstSchema, callout: _callout, fileLimit, readBeforeUpload, showUploadList, beforeUpload, fileList, onFileSuccess, onFieldSubmit, onRemove, onChange, onFileClick, dropzoneProps, overflowList, autoUnzip, disabled: _disabled, noBuildCsvOption, showFilesCount, threeDotMenuItems, onPreviewClick }: {
    accept: any;
    contentOverride: any;
    innerIcon: any;
    innerText: any;
    action: any;
    className?: string | undefined;
    minimal: any;
    validateAgainstSchema: any;
    callout: any;
    fileLimit: any;
    readBeforeUpload: any;
    showUploadList?: boolean | undefined;
    beforeUpload: any;
    fileList: any;
    onFileSuccess?: (() => Promise<void>) | undefined;
    onFieldSubmit?: ((...args: any[]) => void) | undefined;
    onRemove?: ((...args: any[]) => void) | undefined;
    onChange?: ((...args: any[]) => void) | undefined;
    onFileClick: any;
    dropzoneProps?: {} | undefined;
    overflowList: any;
    autoUnzip: any;
    disabled: any;
    noBuildCsvOption: any;
    showFilesCount: any;
    threeDotMenuItems: any;
    onPreviewClick: any;
}): import("react/jsx-runtime").JSX.Element;
