import { noop } from 'lodash-es';
declare namespace _default {
    export { noop as addFilters };
    export let className: string;
    export { noop as clearFilters };
    export { noop as contextMenu };
    export let disabled: boolean;
    export let entities: never[];
    export let extraClasses: string;
    export let filters: never[];
    export let isCopyable: boolean;
    export { noop as isEntityDisabled };
    export let isLoading: boolean;
    export let isSimple: boolean;
    export let isSingleSelect: boolean;
    export let maxHeight: number;
    export let noHeader: boolean;
    export let noSelect: boolean;
    export let noUserSelect: boolean;
    export { noop as onDeselect };
    export { noop as onMultiRowSelect };
    export { noop as onRowClick };
    export { noop as onRowSelect };
    export { noop as onSingleRowSelect };
    export let page: number;
    export let pageSize: number;
    export let reduxFormExpandedEntityIdMap: {};
    export let reduxFormSearchInput: string;
    export let reduxFormSelectedEntityIdMap: {};
    export { noop as removeSingleFilter };
    export let resized: never[];
    export { noop as resizePersist };
    export { noop as setFilter };
    export { noop as setOrder };
    export { noop as setPage };
    export { noop as setPageSize };
    export { noop as setSearchTerm };
    export let showCount: boolean;
    export let style: {};
    export let withCheckboxes: boolean;
    export let withSort: boolean;
}
export default _default;
