#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

bun lint-staged --relative

bun nx affected --target=test --base=master --head=HEAD

# bun auto-changelog -p && git add CHANGELOG.md #tnw - trying to run this only on version bumps